name: remote ssh command
on:
  push:
    branches: [main]
jobs:
  deploy:
    name: Deploy changes to server
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.WEBSVR }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ~/vicinity/ci
            nohup setsid ./rundeploy.sh > rundeploy.log 2>&1 &
            echo "sleeping for 10 sec ..."
            sleep 10
            echo "done..."
